# -*- coding: utf-8 -*-
"""QR-Standar.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WRkzuc47_nCBujWV5nKw4v9fZRTxbrs5
"""

!pip install qrcode[pil]

import qrcode
from IPython.display import display
# Ini library khusus buat nampilin gambar di Colab

# Data QR
data = "https://github.com/edgararya"

# Buat QR
qr = qrcode.QRCode(
    version=1,
    error_correction=qrcode.constants.ERROR_CORRECT_H,
    box_size=10,
    border=4,
)
qr.add_data(data)
qr.make(fit=True)

# Bikin Gambar
img = qr.make_image(fill_color="black", back_color="white")

# TAMPILKAN LANGSUNG (Fitur asik Colab)
display(img)

# Simpan file (ini akan tersimpan di folder sementara Colab)
img.save("edgararya.png")

